-- Run this script in Oracle SQL Developer as SYS with role SYSDBA.
-- The default service used by MoneyBags is Oracle Free's FREEPDB1.
-- For Oracle XE, change FREEPDB1 to XEPDB1 here and in the service URLs.

ALTER SESSION SET CONTAINER = FREEPDB1;

BEGIN
    EXECUTE IMMEDIATE 'CREATE USER MONEYBAGS_TRANSACTION IDENTIFIED BY moneybags';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1920 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE USER MONEYBAGS_LEDGER IDENTIFIED BY moneybags';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1920 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE USER MONEYBAGS_STATEMENT IDENTIFIED BY moneybags';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1920 THEN RAISE; END IF;
END;
/

ALTER USER MONEYBAGS_TRANSACTION QUOTA UNLIMITED ON USERS;
ALTER USER MONEYBAGS_LEDGER QUOTA UNLIMITED ON USERS;
ALTER USER MONEYBAGS_STATEMENT QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER, CREATE VIEW, CREATE PROCEDURE TO MONEYBAGS_TRANSACTION;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER, CREATE VIEW, CREATE PROCEDURE TO MONEYBAGS_LEDGER;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER, CREATE VIEW, CREATE PROCEDURE TO MONEYBAGS_STATEMENT;
